# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0/config/variables.json
Variables:
  ibmMQ:
    # Skip MQ Listener flag: When true, prevents automatic IBM MQ listener initialization at application startup (default: false)
    skipListener: "false"
