# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  ibmmqConnector:
    # Hostname or IP address of the IBM MQ server (e.g., localhost or mq.example.com)
    host: localhost
    # TCP port on which the IBM MQ listener is running (default: 1414)
    port: "1414"
    # MQ channel name used for client connections (e.g., DEV.APP.SVRCONN)
    channel: "DEV.APP.SVRCONN"
    # Name of the Queue Manager to connect to (e.g., QM1)
    queueManager: "QM1"
    # Name of the queue to send/receive messages (e.g., DEV.QUEUE.1)
    queueName: "DEV.QUEUE.1"
    # Username for authenticating with the IBM MQ server
    user: app
    # Password for authenticating with the IBM MQ server
    password: "123456"
